
name: Build and Test project

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:

  build:
    name: Gradle-Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        id: build
        run: |
          echo "executing ./gradlew clean build -x test"
          chmod +x ./gradlew
          ./gradlew clean build -x test
          
          

  test:
    name: Gradle-Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Test with Gradle
        id: test
        run: |
          echo "executing ./gradlew test"
          ./gradlew test




  docker-build-publish:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        id: setup_docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          registry: '192.168.122.198:32000'
          logout: true


      - name: Determine Image Tag
        id: determine_image_tag
        run: |
          
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then                           # It's a tag
            TAG_NAME="${GITHUB_REF##refs/tags/}"                                  # Strip refs/tags/ prefix
          else                                                                    # It's a branch
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//-/g')      
            echo "BRANCH_NAME=${BRANCH_NAME" 
            TAG_NAME="${BRANCH_NAME}-${GITHUB_SHA:0:7}"                           # branch name - commit SHA
            echo "TAG_NAME=${TAG_NAME}"
          fi
          

          COMMIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)    # Not needed
          echo "COMMIT_SHA=${COMMIT_SHA}"
          
          REPO_FULL_NAME=${{ github.repository }}
          REPO_NAME=${REPO_FULL_NAME##*/}
          echo "REPO_NAME=${REPO_NAME}"
          
          IMAGE_TAG="${REPO_NAME}:${TAG_NAME}"
          echo "docker image tag : IMAGE_TAG=${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          

      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}


