
name: .workflow checkout and docker build

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'branch name to checkout'
        required: true
        type: string
      registry_url:
        description: 'docker registry url'
        required: true
        type: string



jobs:

  checkout:

    name: Docker Build Image and Push

    runs-on: ubuntu-latest

    steps:

      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

    
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}


      - name: Set up Docker
        id: setup_docker
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ inputs.registry_url }}"]
              http = true
              insecure = true
          buildkitd-config-inline: |
            [registry."${{ inputs.registry_url }}"]
              http = true
              insecure = true

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_url }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
        continue-on-error: true   # No login for microk8s registry

      - name: Determine Image Tag
        id: determine_image_tag
        run: |
          
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then                           # It's a tag
            TAG_NAME="${GITHUB_REF##refs/tags/}"                                  # Strip refs/tags/ prefix
          else                                                                    # It's a branch
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//-/g')      
            echo "BRANCH_NAME=${BRANCH_NAME}" 
            TAG_NAME="${BRANCH_NAME}-${GITHUB_SHA:0:7}"                           # branch name - commit SHA
            echo "TAG_NAME=${TAG_NAME}"
          fi
          
          
          COMMIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)    # Not needed
          echo "COMMIT_SHA=${COMMIT_SHA}"
          
          REPO_FULL_NAME=${{ github.repository }}
          REPO_NAME=${REPO_FULL_NAME##*/}
          echo "REPO_NAME=${REPO_NAME}"
          
          IMAGE_TAG="${REPO_NAME}:${TAG_NAME}"
          echo "docker image tag : IMAGE_TAG=${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_FULL_TAG=${{ inputs.registry_url }}/${IMAGE_TAG}" >> $GITHUB_ENV


      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
          tags: ${{ inputs.registry_url }}/${{ env.IMAGE_TAG }}






