
name: Java CI with Gradle

on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master


jobs:

  checkout-and-build:
    name: Checkout and Build
    uses: ./.github/workflows/jobs/job-checkout-build.yml
    with:
      branch_name: ${{ github.ref_name }}



  checkout-and-test:
    needs: checkout-and-build
    uses: ./.github/workflows/jobs/job-checkout-test.yml
    with:
      branch_name: ${{ github.ref_name }}



  checkout-and-docker-build:
    needs: checkout-and-build
    uses: ./.github/workflows/jobs/job-checkout-docker-build.yml
    with:
      branch_name: ${{ github.ref_name }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}




